### ISSUE TITLE
Clarification of persistent journals storage location

### ISSUE THREAD

**Issue by srlowe** [balena-io/debugging-masterclass#7]
Hey @hedss , noticed that these two paragraphs seem at odds with each other (if I understood correctly).  First one is probably out of date I guess.

https://github.com/balena-io/debugging-masterclass/blame/3946c584de85f49708f9a72ba9da746eb3737a2d/README.md#L671-L673

https://github.com/balena-io/debugging-masterclass/blame/3946c584de85f49708f9a72ba9da746eb3737a2d/README.md#L742-L745

**Comment by hedss** [comment]
Well done, yep the second should say data partition and not state partition. I'll change this!
